#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/amphora.
#
# SPDX-License-Identifier: Apache-2.0
#
repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.2.0
    hooks:
      - id: pretty-format-java
        args: [--autofix, --google-java-formatter-version, 1.13.0]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.7
    hooks:
      - id: mdformat
        args:
          - --wrap
          - "80"
        additional_dependencies:
          - mdformat-gfm
        exclude: .*/3RD-PARTY-LICENSES/.*|klyshko-mp-spdz/tuple_type_mapping.md$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        exclude: .*/3RD-PARTY-LICENSES/.*|klyshko-operator/charts/klyshko-operator/README.md$|klyshko-mp-spdz/tuple_type_mapping.md$