#
# Copyright (c) 2021 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klyshko-operator
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - klyshko.carbynestack.io
    resources:
      - schedulers
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
  - kind: ServiceAccount
    name: klyshko-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: klyshko-operator
  apiGroup: ""